
tools:
    vcfgl: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/vcfgl_231218/vcfgl/vcfgl"
    picardjar: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/picard.jar"
    bcftools: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/bcftools-1.18/bcftools"
    angsd: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/angsd/angsd"
    gtDiscordance: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/vcfgl/misc/gtDiscordance"

simulation_id: "sim_vcfgl_2312"

# average per site depth
depth: [20 , 10, 2, 1, 0.5, 0.1]

model: "OutOfAfrica_3G09"

contig: "chr22"

# Number of replicates
n_reps: 20

bcftools_gtcheck_error: 0

vcfgl_error_rate: 0.002

def_pops:
    YRI: 50
    CEU: 50
    CHB: 0

pops: ["YRI", "CEU"]

# 1e-X
beta_variance_values_neg_e: [5, 6, 7]


# bcftools call -m  
# ----------------
# file for --group-samples Group samples by population (file with "sample\tgroup")
# sample_groups_tsv: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/simulation/sim/sim_vcfgl_2312/sim_vcfgl_2312_samples_pops.tsv"

bcftools_call_m_prior: 0.0011 #default

perpop_inds_list:
    YRI:
        "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/simulation/sim/sim_vcfgl_2312/sim_vcfgl_2312_YRI_indlist"
    CEU:
        "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/simulation/sim/sim_vcfgl_2312/sim_vcfgl_2312_CEU_indlist"

