
tools:
    vcfgl: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/vcfgl/vcfgl"
    picardjar: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/picard.jar"
    bcftools: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/bcftools-1.18/bcftools"
    angsd: "/maps/projects/lundbeck/scratch/pfs488/vcfgl/vcfgl_paper_analyses/tools/angsd/angsd"


simulation_id: "sim_vcfgl_2309"

# average per site depth
# depth: ["inf", 100, 20 , 10, 2, 1, 0.5, 0.1]
depth: [20 , 10, 2, 1, 0.5, 0.1]

model: "OutOfAfrica_3G09"

contig: "chr22"

# Number of replicates
n_reps: 20
# n_reps: 1

vcfgl_error_rate: 0.002

def_pops:
    YRI: 50
    CEU: 50
    CHB: 0


# 1e-X
beta_variance_values_neg_e: [6, 7]



# ANGSD SNP CALLING ---------------------- #
#
SNP_calling_SNP_pval: "1e-6"

# ---------------------------------------- #
