{
	"__default__" :
	{
		"mem_mb" : 4000,
		"n" : 1,
		"tasks" : 1,
		"name" : "PROJECT_vcfgl-RULE_{rule}-JOB_{jobid}",
		"logfile": "sim/slurm_logs/logs_231006_203953/smk_{rule}_%j.out",
		"errfile": "sim/slurm_logs/logs_231006_203953/smk_{rule}_%j.err",
		"time": "13:00:00"
	}
}
